controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

menu:
    path: /menu
    controller: App\Controller\MenuController::menu